APP_VERSION = "3.4.1"
GITHUB_OWNER = "ahansardar"
GITHUB_REPOSITORY = "SafeRide"
INSTALLER_ASSET = "SafeRide-Setup-x64.exe"
INSTALLER_CHECKSUM_ASSET = "SafeRide-Setup-x64.sha256.txt"
PORTABLE_ASSET = "SafeRide-Portable-x64.exe"
PORTABLE_CHECKSUM_ASSET = "SafeRide-Portable-x64.sha256.txt"
